### ISSUE TITLE
Remove "Begone, Evil! (Disable Corruption Spread)", duplicated function in Quality Of Terraria

### ISSUE THREAD

**Issue by PhantomDergwulf** [bromeex/TheBereftSouls#27]
Quality Of Terraria has the same functionality and as such this mod is redundant
![image](https://github.com/user-attachments/assets/baed6d3b-b43f-4daa-9728-3728147157f8)

**Comment by 1Git2Clone** [comment]
Thank you, I'll directly commit the changes.
